name: Build all templates

on:
  pull_request:
    branches: [main]

jobs:
  build-templates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build all packages
        run: npm run build
